version: "3"

tasks:
  default:
    cmds:
      - task: build

  build:
    cmds:
      - go build -o bin/guac-ai-mole ./cmd/server/main.go

  test:
    cmds:
      - go test ./...

  lint:
    cmds:
      - golangci-lint run

  run:
    cmds:
      - go run ./cmd/server/main.go

  clean:
    cmds:
      - rm -rf bin/

  docker-build:
    cmds:
      - docker build -t guac-ai-mole .

  docker-run:
    cmds:
      - docker run guac-ai-mole

  dev:
    cmds:
      - go run main.go
